// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraneeLibrary.Data;

#nullable disable

namespace TraneeLibrary.Migrations
{
    [DbContext(typeof(LocalDBContext))]
    [Migration("20251213014545_AddObjectTraningTempalteToTraningsession")]
    partial class AddObjectTraningTempalteToTraningsession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("TraneeLibrary.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupOfMuscle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestBetweenSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TraningSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TraningSessionId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("TraneeLibrary.ExerciseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupOfMuscle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestBetweenSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetReps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainingTemplateId");

                    b.ToTable("ExerciseTemplates");
                });

            modelBuilder.Entity("TraneeLibrary.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("TraneeLibrary.TrainingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RestBetweenSets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrainingTemplates");
                });

            modelBuilder.Entity("TraneeLibrary.TraningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestBetweenExercise")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrainingTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainingTemplateId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TraneeLibrary.Exercise", b =>
                {
                    b.HasOne("TraneeLibrary.TraningSession", "TraningSession")
                        .WithMany("Exercises")
                        .HasForeignKey("TraningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraningSession");
                });

            modelBuilder.Entity("TraneeLibrary.ExerciseTemplate", b =>
                {
                    b.HasOne("TraneeLibrary.TrainingTemplate", "TrainingTemplate")
                        .WithMany("ExerciseTemplates")
                        .HasForeignKey("TrainingTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingTemplate");
                });

            modelBuilder.Entity("TraneeLibrary.Set", b =>
                {
                    b.HasOne("TraneeLibrary.Exercise", "Exercise")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("TraneeLibrary.TraningSession", b =>
                {
                    b.HasOne("TraneeLibrary.TrainingTemplate", "TrainingTemplate")
                        .WithMany()
                        .HasForeignKey("TrainingTemplateId");

                    b.Navigation("TrainingTemplate");
                });

            modelBuilder.Entity("TraneeLibrary.Exercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("TraneeLibrary.TrainingTemplate", b =>
                {
                    b.Navigation("ExerciseTemplates");
                });

            modelBuilder.Entity("TraneeLibrary.TraningSession", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
